version: "3"

services:
######################DB Container#########################
  zabbix-db:
    image: mariadb:10.6
    container_name: zabbix-db
    hostname: zabbix-db
    volumes:
      - ./db:/var/lib/mysql
      - ./backup_db:/backup_db
    ports:
      - '3306:3306'
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin']
    env_file:
      - ./env/zabbix.env
    #restart: always
    restart: unless-stopped
################Zabbix-server Container#####################
  zabbix-server:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server
    hostname: zabbix-server
    ports:
      - "10051:10051"
    env_file:
      - ./env/zabbix.env
#    restart: always
    restart: unless-stopped
    links:
      - zabbix-db
    depends_on:
      - zabbix-db

################Zabbix-WEB Container########################
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: zabbix-web
    hostname: zabbix-web
    ports:
      - "9396:8080"
      - "52402:443"
    env_file:
      - ./env/zabbix.env
    restart: unless-stopped
#    restart: always
    links:
      - zabbix-server
      - zabbix-db
    depends_on:
      - zabbix-server

################Zabbix-agent Container########################
  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-6.0-latest
    container_name: zabbix-agent
    hostname: zabbix-agent
    ports:
      - "10050:10050"
    env_file:
      - ./env/zabbix.env
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_DEBUGLEVEL=1
    links:
      - zabbix-server
      - zabbix-db
    depends_on:
      - zabbix-server

################Zabbix-proxy Container########################
#  zabbix-proxy:
#    image: zabbix/zabbix-proxy-sqlite3:ubuntu-latest
#    container_name: zabbix-proxy
#    hostname: home-proxy
#    ports:
#      - "10051:10051"
#    env_file:
#      - ./env/zabbix-proxy.env
#    restart: always

#  zabbix-proxy-agent:
#    image: zabbix/zabbix-agent:alpine-latest
#    container_name: zabbix-proxy-agent
#    hostname: home-proxy-agent
#    ports:
#      - "10050:10050"
#    privileged: true
#    pid: "host"
#    restart: always
#    environment:
#      - ZBX_SERVER_HOST=home-proxy
#      - ZBX_DEBUGLEVEL=1

############ PHP my admin###################################
#  phpmyadmin:
#    image: phpmyadmin
#    container_name: zabbix-php_my_admin
#    hostname: zabbix-php_my_admin
#    ports:
#      - "8085:80"
#    restart: always
#    links:
#      - zabbix-db
#    env_file:
#      - ./env/zabbix.env
#    environment:
#      - PMA_ARBITRARY=1
#    depends_on:
#      - zabbix-db
